---


- name: "Copiando arquivo de repositório do pacote {{ app_package }}"
  copy:
    src: "mysql-workbench-community-suse.repo"
    dest: "/etc/zypp/repos.d/mysql-workbench-community.repo"
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - repo


- name: Atualizando todos os repositorios
  zypper_repository:
    repo: '*'
    runrefresh: yes
    overwrite_multiple: yes
    auto_import_keys: yes
  become: true
  tags:
    - repo
    - update

    
- name: "Instalando o pacote {{ app_package }}"
  zypper:
    name: "{{ app_package }}"
    state: present
    force: yes
    update_cache: yes
  become: true
  tags:
    - workbench